-- USERS

-- create user chema
CREATE SCHEMA users;
GO

-- create table individuals under users chema
CREATE TABLE USERS.INDIVIDUALS (
	SSN VARCHAR(15) PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	MIDDLE_NAME VARCHAR(50),
	[STATUS] INT CHECK([STATUS] IN (10, 60)) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	REGISTER_DATE DATE NOT NULL,
	TERMINATED_DATE DATE,
	ADDRESS_CODE VARCHAR(20) NOT NULL
)
GO


-- create accounts table under users schema
CREATE TABLE USERS.ACCOUNTS (
	ACCOUNT_ID INT PRIMARY KEY IDENTITY(1, 1),
	SSN VARCHAR(15) FOREIGN KEY REFERENCES USERS.INDIVIDUALS(SSN) UNIQUE,
	USERNAME VARCHAR(100) NOT NULL,
	[PASSWORD] VARCHAR(100) NOT NULL,
	CREATED_DATE DATE NOT NULL,
	[STATUS] INT CHECK([STATUS] IN (10, 60)) NOT NULL,
	UPDATED_DATE DATE,
	TERM_DATE DATE
)
GO